engines:
  radon:
    enabled: true
    config:
      python_version: 2
      threshold: C
  pep8:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
